-- Supabase SQL Editor にそのまま貼り付けて実行してください。

create table if not exists public.youtube_videos (
    video_id text primary key,
    title text not null,
    description text,
    channel_name text,
    channel_id text,
    published_at timestamptz,
    youtube_published_at timestamptz,
    actual_start_time timestamptz,
    scheduled_start_time timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.records (
    id bigint generated by default as identity primary key,
    user_id text not null,
    url text not null,
    video_id text not null references public.youtube_videos(video_id),
    title text not null,
    description text,
    channel_name text,
    channel_id text,
    published_at timestamptz,
    content_type text not null,
    amount integer not null,
    tags text,
    ai_confidence real,
    ai_reason text,
    created_at timestamptz not null default now(),
    unique(user_id, video_id)
);

create table if not exists public.calendar_checks (
    user_id text not null,
    date date not null,
    status text not null,
    primary key(user_id, date)
);

create table if not exists public.user_settings (
    user_id text primary key,
    saving_rules jsonb not null default '{}'::jsonb,
    content_type_icons jsonb not null default '{}'::jsonb,
    tag_colors jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.api_usage (
    user_id text not null,
    usage_date date not null,
    count integer not null default 0,
    primary key(user_id, usage_date)
);

-- Streamlit Community Cloud 側から service_role key でアクセスするため、
-- このアプリではDBアクセスをサーバー側に限定します。
-- service_role key は絶対にGitHubへ公開しないでください。

-- 1日API上限を原子的にカウントする関数
create or replace function public.consume_api_quota(
    p_user_id text,
    p_usage_date date,
    p_limit integer
)
returns json
language plpgsql
security definer
as $$
declare
    new_count integer;
begin
    insert into public.api_usage(user_id, usage_date, count)
    values (p_user_id, p_usage_date, 1)
    on conflict (user_id, usage_date)
    do update set count = public.api_usage.count + 1
    returning count into new_count;

    if new_count > p_limit then
        update public.api_usage
        set count = count - 1
        where user_id = p_user_id and usage_date = p_usage_date;
        return json_build_object('allowed', false, 'count', p_limit);
    end if;

    return json_build_object('allowed', true, 'count', new_count);
end;
$$;
